_target_: src.models.dygformer.DyGFormerModule


time_feat_dim: 100
channel_embedding_dim: 50
output_dim: 172
patch_size: 1
num_layers: 2
num_heads: 2
dropout: 0.1
max_input_sequence_length: 32


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0
