_target_: src.models.graphmixer.GraphMixerModule


time_feat_dim: 100
output_dim: 172
num_layers: 2
token_dim_expansion_factor: 0.5
channel_dim_expansion_factor: 4.0
dropout: 0.5
num_neighbors: 30
num_tokens: ${model.num_neighbors}
time_gap: 2000
sample_neighbor_strategy: recent

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005
  weight_decay: 0.0
