_target_: src.models.tgat.TGATModule


time_feat_dim: 100
num_neighbors: 20
num_layers: 2
num_heads: 2
dropout: 0.1
sample_neighbor_strategy: recent
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0
